train_file: D:/projects/Torch/Image Captioning vol.2/data/datasets/train-40.pt
dev_file: D:/projects/Torch/Image Captioning vol.2/data/datasets/dev-40.pt
logs_dir: D:/projects/Torch/Image Captioning vol.2/logs
runs_dir: D:/projects/Torch/Image Captioning vol.2/runs
checkpoint_file: null